### ISSUE TITLE
Convert to SDR

### ISSUE THREAD

**Issue by GatCode** [pecostm32/FNIRSI-1013D-Hack#5]
Hi,
do you think it would be possible/feasible to push the raw data out over the usb connector and therefore create a SDR? This would allow the oscilloscope to be used with Gnuradio – inspired by: https://github.com/jmfriedt/gr-oscilloscope38
Thanks!

**Comment by pecostm32** [comment]
I don't think this will work. The system is not fast enough to do this.

**Comment by GatCode** [comment]
Alright, thank you very much.
